config/routes.rb
Rails.application.routes.draw do
  if Rails.env.staging?
    mount Lockup::Engine, at: '/lockup'
  end

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  require 'sidekiq/web'

  namespace :system do
    authenticate(:admin) do
      mount Sidekiq::Web => '/sidekiq'
    end
  end

  mount Decidim::Core::Engine => '/'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :help_sections, only: :show, module: 'decidim'

  Decidim::Admin::Engine.routes.draw do
    resource :survey
    resources :posts, controller: 'blog_posts'
    resources :newsletters, controller: 'user_exports', only: %i[index create]
  end

  resources :posts, controller: 'ema/blog/blog_posts', only: %i[index show], as: 'ema_blog_posts'

  get 'healthcheck' => 'healthcheck#index'
end

app/controllers/decidim/admin/user_exports_controller.rb
# frozen_string_literal: true

module Decidim
  module Admin
    class UserExportsController < Decidim::Admin::ApplicationController
      before_action :enforce_permission

      def index
        @count = users_for_export.count
      end

      def create
        send_data ExportUsers.new(users_for_export).call, filename: "decidim-users-#{Date.today}.csv"
      end

      private

      def users_for_export
        Decidim::User.confirmed
        .not_deleted
        .where(organization: @current_organization)
        .where.not(newsletter_notifications_at: nil)
        .order(id: :asc)
      end

      def enforce_permission
        enforce_permission_to :update, :organization
      end
    end
  end
end

app/views/decidim/admin/user_exports/index.html.haml
.card
  .card__content
    .card-divider
      %h2.card-title
        = t('title', scope: 'ema.user_exports.admin.index')


    .card-section
      %p
        = t('description', scope: 'ema.user_exports.admin.index')

      %p
        = t('count', scope: 'ema.user_exports.admin.index', count: @count)

      = form_for :user_export, url: newsletters_path do |f|
        = f.submit t('new_user_export', scope: 'ema.user_exports.admin.index')